default_language_version:
  python: python3.10
exclude: (docs\/js|patches)\/
repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      args: [--preview]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(css|html|js|md|pug)$
        additional_dependencies:
          - prettier@3.0.3
          - "@prettier/plugin-pug@3.0.0"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.49.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.49.0
          - eslint-config-prettier@9.0.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
