default_language_version:
  python: python3.12
exclude: (docs\/js|patches)\/
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format # formatter
      - id: ruff # linter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(css|html|js|md|pug)$
        additional_dependencies:
          - prettier@3.0.3
          - "@prettier/plugin-pug@3.0.0"
          - "@ianvs/prettier-plugin-sort-imports@4.1.0"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.49.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.49.0
          - eslint-config-prettier@9.0.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml
