name: speechviz
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - jupyter
  - jupyterlab
  - numpy
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - pip:
    - pyannote.audio
    - speechbrain
